Append the weapon to the end of the "kill" message
DBrueberg/ZombieWar pull request #37
Opened 2021-12-12 23:26 UTC by flierc-csp

Append the weapon to the end of the string stating that a Character has killed another if the attacker is a survivor.
Closes #35

2021-12-12 23:47 UTC, DBrueberg requested changes
Great job, found a couple things.
The printout on line 106 and 107 in Match will print out on Weapon kill if lets say it is a Child and CommonInfect:
"child 0 killed common infect 1Axe"

It should read something like
"child 0 killed common infect 1 with the Axe" or
"child 0 used the Axe to kill common infect 1"

2021-12-13 17:28 UTC, DBrueberg requested changes
Line 101 needs to be cast first to Survivor, then .getWeapon() method call. As shown below:

Weapon weapon = ((Survivor) currentAttacker).getWeapon();

2021-12-14 15:50 UTC, DBrueberg approved these changes
Looks great.

2021-12-14 15:58 UTC, noko12312 approved these changes

2021-12-14 19:45 UTC, dietschc approved these changes

2021-12-14 22:30 UTC, merged